# Decision Tree Regresor

## Import all required library

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score,mean_squared_error
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor

## Importing the dataset

In [ ]:
data =pd.read_csv('Chocolate.csv')
data.head()

,Sales Person,Country,Product,Date,Amount,Boxes Shipped
0,Jehu Rudeforth,UK,Mint Chip Choco,04/01/2022,"$5,320.00",180
1,Van Tuxwell,India,85% Dark Bars,01/08/2022,"$7,896.00",94
2,Gigi Bohling,India,Peanut Butter Cubes,07/07/2022,"$4,501.00",91
3,Jan Morforth,Australia,Peanut Butter Cubes,27/04/2022,"$12,726.00",342
4,Jehu Rudeforth,UK,Peanut Butter Cubes,24/02/2022,"$13,685.00",184

## Encoder

In [23]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Sales Person'] = le.fit_transform(data['Sales Person'])
data['Country'] =le.fit_transform(data['Country'])
data['Product'] =le.fit_transform(data['Product'])
data.head()

   Sales Person  Country  Product        Date      Amount  Boxes Shipped
0            13        4       14  04/01/2022   $5,320.00            180
1            23        2        2  01/08/2022   $7,896.00             94
2             9        2       17  07/07/2022   $4,501.00             91
3            12        0       17  27/04/2022  $12,726.00            342
4            13        4       17  24/02/2022  $13,685.00            184

## Split the data in X and Y

In [24]:
x =data.drop(['Boxes Shipped','Date','Amount'], axis=1)
y = data['Boxes Shipped']

In [ ]:
X_train, X_test, y_train, Y_test =train_test_split(X ,y ,test test_size=0.2, random_state=42)